#!/usr/bin/env Rscript

library(optparse)
library(rpiret)


option_list <- list(
  make_option(c("-d", "--dir"), action = "store",
              help = "directory containing results of EdgeR or DESeq2"),
  make_option(c("-m", "--method"), action = "store",
              help = "output of which results to conduct gage analysis on"),
  make_option(c("-c", "--org_code"), action = "store",
              help = "kegg orgainsm code to download pathway information")
    )

opt <- parse_args(OptionParser(option_list = option_list))

#
dir <- opt$dir
method <- opt$method
org <- opt$org_code

#==============================================================================#
# create the output directory
# ifelse(!dir.exists(out_dir), dir.create(out_dir), print("already exist"))
#==============================================================================#

# grab fold change files
if ( method == "edgeR"){
    fcs = list.files(path = dir, pattern = "gene_*_sig.csv", full.names = TRUE)
    for (fc in fcs) {
        out_dir = base::strsplit(fc, split = ".csv", fixed = TRUE)[[1]][1]
        ifelse(!dir.exists(out_dir), dir.create(out_dir), print("already exist"))
        rpiret::gage_analysis(fc, "edgeR", org, out_dir) 
    }
} else if (method == "DESeq2")
{   
    fcs = list.files(path = dir, pattern = "*gene__sig.csv", full.names = TRUE)
    for (fc in fcs) {
        out_dir = base::strsplit(fc, split = ".csv", fixed = TRUE)[[1]][1]
        ifelse(!dir.exists(out_dir), dir.create(out_dir), print("already exist"))
        rpiret::gage_analysis(fc, "DESeq2", org, out_dir) 
    }
}
